Ruby/Rails/bath_events/config/routes.rb
Rails.application.routes.draw do
  resources :events, :users

  root 'welcome#index'

end

Ruby/Rails/bath_events/app/models/event.rb
class Event < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5 }
end

Ruby/Rails/bath_events/app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }

	validates :name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, length: { maximum: 255 },
	                    format: { with: VALID_EMAIL_REGEX },
	                    uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: { minimum: 6 }
end

Ruby/Rails/bath_events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby/Rails/bath_events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(event_params)
 
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  private
    def event_params
      params.require(:event).permit(:title, :venue, :datetime, :cost, :description)
    end
end

Ruby/Rails/bath_events/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	end

	def create
	end
	
end

Ruby/Rails/bath_events/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Ruby/Rails/bath_events/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/Rails/bath_events/app/helpers/events_helper.rb
module EventsHelper
end

Ruby/Rails/bath_events/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/Rails/bath_events/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Ruby/Rails/bath_events/app/views/events/index.html.erb
<h1>Listing events</h1>

<%= link_to 'New article', new_event_path %>
 
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Venue</th>
    <th>DateTime</th>
    <th>Cost</th>
  </tr>
 
  <% @events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.venue %></td><td>
      <td><%= event.datetime %></td>
      <td><%= event.cost %></td>
    </tr>
  <% end %>
</table>

Ruby/Rails/bath_events/app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for :event, url: events_path do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:</h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :venue %><br>
    <%= f.text_area :venue %>
  </p>

  <p>
    <%= f.label :datetime %><br>
    <%= f.datetime_field :datetime %>
  </p>

  <p>
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </p>

   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', events_path %>

Ruby/Rails/bath_events/app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>DateTime:</strong>
  <%= @event.datetime %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @event.cost %>
</p>

<%= link_to 'Back', events_path %>

Ruby/Rails/bath_events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BathEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ruby/Rails/bath_events/app/views/users/new.html.erb
<h1>New User!!</h1>

Ruby/Rails/bath_events/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Bath Events', controller: 'events' %>